// Generated by Springs Advertising Admin — 5/16/2026, 4:41:47 PM
// Upload this file to your server to apply images on all devices.
window.SPRING_IMAGES={
  "idx_hero": "https://images.squarespace-cdn.com/content/v1/5c7976ec11f78465c3ab8a2d/374bf0e1-70cc-4d06-85e7-29668692b586/Dubai_December+12%2C+2025_12374.jpg",
  "proj_veh_1": "https://i.postimg.cc/L4vPGcc3/PHOTO-2026-05-16-08-34-48-2.jpg",
  "proj_veh_2": "https://i.postimg.cc/CMJMFSLd/PHOTO-2026-05-16-08-34-49.jpg",
  "proj_veh_3": "https://i.postimg.cc/zftmsXkG/IMG-8011.jpg",
  "proj_veh_4": "https://www.springsadvt.com/CMS/products/projects-06344602072014.jpg",
  "proj_veh_5": "https://i.postimg.cc/28RpRtnd/PHOTO-2026-05-16-08-34-48.jpg"
};
